### ISSUE TITLE
Remove caveat on npm page

### ISSUE THREAD

**Issue by rreusser** [scijs/gauss-quadrature#1]
@mikolalysenko, it looks like you implemented durand-kerner to overcome the issues with numeric.js. The npm page still has the caveat about the module being worthless. I think it just needs:
1. Bump version to 1.0
2. Publish to npm

I'm glad to do that if my casual understanding is correct. It has one dependent (hoarders) that should maybe be updated correspondingly.

**Comment by mikolalysenko** [comment]
You can do the honors, and don't worry about hoarders.  It is a joke that @tmpvar made a long time ago.

**Comment by tmpvar** [comment]
oh, haha, that was not a :trollface: - I just wanted to have all of @mikolalysenko's code at the time so I could read through it on the plane

**Comment by rreusser** [comment]
Aww, disappointing. I figured it might be a good read!
